// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoEOal5xVc2JeAY2CrdDMJYH0fyWAJsO4',
    appId: '1:554714373782:web:56f22b4a30a46eb46eecb7',
    messagingSenderId: '554714373782',
    projectId: 'pharmacy-24093',
    authDomain: 'pharmacy-24093.firebaseapp.com',
    storageBucket: 'pharmacy-24093.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsYw2E845slzM6NvDm_7zjX9a6_b0-a6o',
    appId: '1:554714373782:android:afda221a0ba4cc766eecb7',
    messagingSenderId: '554714373782',
    projectId: 'pharmacy-24093',
    storageBucket: 'pharmacy-24093.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYuFsV5fE5A5mJBflcgEUsdDBMAT2m1N8',
    appId: '1:554714373782:ios:727d9241399efcfb6eecb7',
    messagingSenderId: '554714373782',
    projectId: 'pharmacy-24093',
    storageBucket: 'pharmacy-24093.appspot.com',
    iosClientId: '554714373782-8agflj869cke6faljj6lvje1u02cvdus.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanArch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYuFsV5fE5A5mJBflcgEUsdDBMAT2m1N8',
    appId: '1:554714373782:ios:727d9241399efcfb6eecb7',
    messagingSenderId: '554714373782',
    projectId: 'pharmacy-24093',
    storageBucket: 'pharmacy-24093.appspot.com',
    iosClientId: '554714373782-8agflj869cke6faljj6lvje1u02cvdus.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanArch',
  );
}
